config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root "home#index"
  root 'posts#index'


  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: :post_id}
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  validates :photo, :title, :description, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone_number, presence: true, numericality: { only_integer: true, message: "is not a number" }, length: { is: 10, message: "must be 10 digits" }
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  end

  def authenticate_user
    if current_user.nil?
      flash[:error] = 'You must be signed in to view that page.'
      redirect_to new_user_session_path
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @bookmark = current_user.bookmarks.new(post: @post)

    if @bookmark.save
      redirect_to @bookmark.post, notice: 'Post Booked'
    else
      redirect_to @bookmark.post, alert: 'Unable to Book post'
    end
  end

  def destroy
    @bookmark = current_user.bookmarks.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.post, notice: 'Post Booked'
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :is_owner?, only: [:edit, :update, :destroy]
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params.merge(user_id: current_user.id))
    if @comment.save && @comment.valid?
      redirect_to @post
    else
      flash[:alert] = "Invalid params"
      redirect_to @post
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    if @comment.valid?
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  private
  def comment_params
    params.require(:comment).permit(:description, :user_id, :post_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end




    def is_owner?
      # redirect_to root_path if Comment.find(params[:id]).user != current_user
      unless @comment.user == current_user || @post.user == current_user
        redirect_to root_path
        return
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.new(post: @post)

    if @like.save
      redirect_to @like.post, notice: 'Post liked'
    else
      redirect_to @like.post, alert: 'Unable to like post'
    end
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @like.destroy
    redirect_to @like.post, notice: 'Post unliked'
  end

  # def like_params
  #     params.require(:like).permit(:post_id)
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, only: [:new, :create]
  # before_action :is_owner?, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end
  def create
    @post = current_user.posts.create(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post= Post.find(params[:id])
  end


  private
  def post_params
    params.require(:post).permit(:user_id, :photo, :title, :description)
  end

  # def is_owner?
  #   redirect_to root_path if Post.find(params[:id]).user != current_user
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts/downvotes_helper.rb
module Posts::DownvotesHelper
end

app/helpers/posts/upvotes_helper.rb
module Posts::UpvotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1 class="text-2xl mb-4 font-bold">Edit Post</h1>

<div class="md:w-[40%]">
  <%= simple_form_for [@post,@comment] do |f| %>
    <%= f.input :description, label: 'Comment', placeholder: 'edit a comment...', label_html: {class: 'mt-4'}, input_html: {class: 'mt-2 md:max-w-[50%]'} %>
    <%= f.submit 'Update', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800' %>
<% end %>
</div>







app/views/home/index.html.erb
<div class="m-64">

<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MediumCloneApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "main.min", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script
      src="https://kit.fontawesome.com/14dea2b7a9.js"
      crossorigin="anonymous"
    ></script>

    <link
    crossorigin="crossorigin"
    href="https://fonts.gstatic.com"
    rel="preconnect"
  />

  <link
    as="style"
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
    rel="preload"
  />

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
    rel="stylesheet"
  />

  <link
    rel="stylesheet"
    href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
  />

  <link
    crossorigin="anonymous"
    href="/assets/styles/main.min.css"
    media="screen"
    rel="stylesheet"
  />

  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>

  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/atom-one-dark.min.css"
  />

  <script>
    hljs.initHighlightingOnLoad();
  </script>

  <!--Alpine Js V3-->
  <script src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
  </head>

  <body>
    

    







     <p class="notice text-red"><%= notice %></p>
     <p class="alert text-red"><%= alert %></p>
     <%= render 'shared/nav'%>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div>
      <div class="container mx-auto">
        <div class="py-16 lg:py-20">
          <div>
            <img src="/assets/img/icon-blog.png" alt="icon envelope" />
          </div>

          <h1 class="pt-5 font-body text-4xl font-semibold text-primary dark:text-white md:text-5xl lg:text-6xl">
            Blog
          </h1>

          <div class="pt-3 sm:w-3/4">
            <p class="font-body text-xl font-light text-primary dark:text-white">
              Articles, tutorials, snippets, rants, and everything else. Subscribe for
              updates as they happen.
            </p>
          </div>

          <form class="flex flex-col py-12 sm:flex-row">
            <input type="email" id="subscribe" placeholder="Drop that email here…"
              class="w-full border border-primary bg-grey-lightest px-5 py-4 font-body font-light text-primary placeholder-primary transition-colors focus:border-secondary focus:outline-none focus:ring-2 focus:ring-secondary dark:border-secondary sm:w-1/2" />
            <button type="submit"
              class="mt-5 bg-secondary px-10 py-4 font-body text-xl font-semibold text-white hover:bg-green sm:mt-0 md:text-2xl">
              Subscribe
            </button>
          </form>

          <div class="pt-8 lg:pt-12">
            
            <% @posts.each do |post|%>
              <div class="border-b border-grey-lighter pb-8">
                <span
                  class="mb-4 inline-block rounded-full bg-green-light px-2 py-1 font-body text-sm text-green">category</span>
                <%= link_to post_path(post), class: "block font-body text-lg font-semibold text-primary transition-colors hover:text-green dark:text-white dark:hover:text-secondary" do %>
                  <%= post.title%>
                  <% end %>
                  
                <div class="flex items-center pt-4">
                  <p class="pr-2 font-body font-light text-primary dark:text-white">
                    <%= post.created_at.strftime("%B %d, %Y") %>
                  </p>
                  <span class="font-body text-grey dark:text-white">//</span>
                  <p class="pl-2 font-body font-light text-primary dark:text-white">
                    4 min read
                  </p>
                </div>
              </div>
            <%end%>
            
          </div>

          <script src="/assets/js/main.js"></script>
</div>




















app/views/posts/new.html.erb
<h1 class="text-2xl mb-20 font-bold">New Post</h1>
<div class="flex justify-center md:w-[40%]">


<%= simple_form_for @post do |f| %>
  <%= f.input :photo %>
  <%= f.input :title %>
  <%= f.input :description, input_html: { rows: 4 } %>
  <%= f.submit 'Post',class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800'  %>
<% end %>
</div>






app/views/posts/show.html.erb
<div>
  <div class="container mx-auto">
      <div class="pt-16 lg:pt-20">
        <div class="border-b border-grey-lighter pb-8 sm:pb-12">
          <span
            class="mb-5 inline-block rounded-full bg-green-light px-2 py-1 font-body text-sm text-green sm:mb-8">category</span>
          <h2
            class="block font-body text-3xl font-semibold leading-tight text-primary dark:text-white sm:text-4xl md:text-5xl">
            <%= @post.title%>
            
          </h2>
          <div class="flex items-center pt-5 sm:pt-8">
            <p class="pr-2 font-body font-light text-primary dark:text-white">
              <%= @post.created_at.strftime("%B %d, %Y") %>
            </p>
            <span class="vdark:text-white font-body text-grey">//</span>
            <p class="pl-2 font-body font-light text-primary dark:text-white">
              4 min read
            </p>
            <%# <%= @post.user.email.split('@').first %>
          </div>
        </div>
        <div class="prose prose max-w-none border-b border-grey-lighter py-8 dark:prose-dark sm:py-12">
          <%= image_tag @post.photo %>
          <p class="text-justify"><%= @post.description %></p>
        </div>
        <%# likes %>
      <div class="flex items-center">
        <div>
        <% if current_user && @post.likes.where(user_id: current_user.id).empty? %>
          <%= button_to "Like", post_likes_path(@post), method: :post,class:"text-black bg-black-700 hover:bg-black-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"%>
        <% else %>
          <% like = @post.likes.find_by(user_id: current_user.id) %>
          <%= button_to "Unlike", post_like_path(@post, like), method: :delete,class:"text-black bg-black-700 hover:bg-black-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
        <% end %>
        <p><%= pluralize @post.likes.count, "like" %></p>
      </div>
          <%# bookmark %>


        <div class="flex items-center">
        <div>
        <% if current_user && @post.bookmarks.where(user_id: current_user.id).empty? %>
          <%= button_to "Bookmark", post_bookmarks_path(@post), method: :post,class:"text-black bg-black-700 hover:bg-black-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"%>
        <% else %>
          <% bookmark = @post.bookmarks.find_by(user_id: current_user.id) %>
          <%= button_to "UnBook", post_bookmark_path(@post, bookmark), method: :delete,class:"text-black bg-black-700 hover:bg-black-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
        <% end %>
        <p><%= pluralize @post.bookmarks.count, "Bookmark" %></p>
      </div>







    </div>

          <div class="px-5 py-5">
            <% @post.comments.each do |comment| %>
              <div class="px-2">
                <p class="mb-5">
                  <%= comment.user.email.split('@').first %> 
                  <%= comment.description %>
                </p>
                <%if comment.user == current_user%>
                  <%= link_to 'Edit |', edit_post_comment_path(post_id: @post.id, id: comment.id) %>
                <%end%>
                <% if comment.user == current_user || @post.user == current_user %>
                  <%= link_to 'Delete', post_comment_path(post_id: @post.id, id: comment.id), method: :delete,data: { turbo_confirm: 'Are you sure?', "turbo-method": :delete }%>
                <%end%>
              </div>
            <% end %>
          </div>
          <%if current_user%>
            <%= simple_form_for Comment.new, url: post_comments_path(@post), method: :post do |f| %>
              <%= f.input :description, label: 'Comment', placeholder: 'Add a comment', label_html: {class: 'mt-4'}, input_html: {class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-md focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-50 dark:border-gray-600 dark:placeholder-gray-500 dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500"} %>
              <%= f.submit 'Post' %>
            <% end %>
          <%end%>
        </div>
    </div>
</div>







app/views/shared/_nav.html.erb
<div class="container mx-auto">
      <div class="flex items-center justify-between py-6 lg:py-10">
        <a href="/" class="flex items-center">
          <span href="/" class="mr-2">
            <img src="/assets/img/logo.svg" alt="logo" />
          </span>
          <p class="hidden font-body text-2xl font-bold text-primary dark:text-white lg:block">
            Medium Clone
          </p>
        </a>
         <div class="flex items-center lg:hidden">
          <i class="bx mr-8 cursor-pointer text-3xl text-primary dark:text-white" @click="themeSwitch()"
            :class="isDarkMode ? 'bxs-sun' : 'bxs-moon'"></i>

          <svg width="24" height="15" xmlns="http://www.w3.org/2000/svg" @click="isMobileMenuOpen = true"
            class="fill-current text-primary dark:text-white">
            <g fill-rule="evenodd">
              <rect width="24" height="3" rx="1.5" />
              <rect x="8" y="6" width="16" height="3" rx="1.5" />
              <rect x="4" y="12" width="20" height="3" rx="1.5" />
            </g>
          </svg>
        </div>
        <div class="hidden lg:block">
          <ul class="flex items-center">

            <%# <li class="group relative mr-6 mb-1">
              <div
                class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow">
              </div>
              <a href="/"
                class="relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary">Intro</a>
            </li> %>
            <% if user_signed_in? %>
                <li class="group relative mr-6 mb-1">
                <div
                    class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow">
                </div>
                <%= link_to "Blog", posts_path,class: "relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"%>
                </li>
                <li class="group relative mr-6 mb-1">
                <div
                    class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow">
                </div>
                <%= link_to "New Post", new_post_path,class: "relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary" %>
                </li>

                <li class="group relative mr-6 mb-1">
                <div
                    class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow">
                </div>
                <%= link_to "Edit Profile",edit_user_registration_path,class: "relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary" %>
                </li>

                <li class="group relative mr-6 mb-1">
                <div
                    class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow">
                </div>
                <%= link_to "Sign Out",destroy_user_session_path, method: :delete, class: "relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary", data: { turbo_confirm: 'Are you sure?', "turbo-method": :delete } %>
                </li>
               <%else%>
                <li class="group relative mr-6 mb-1">
                <div
                    class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow">
                </div>
                <%= link_to "Sign Up",new_user_registration_path,class: "relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary" %>
                </li>

                <li class="group relative mr-6 mb-1">
                <div
                    class=" absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow">
                </div>
                <%= link_to "Log In",new_user_session_path, method: :delete, class: "relative z-30 block px-2 font-body text-lg font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary" %>
                </li>
            <%end%>
            <li>
              <i class="bx cursor-pointer text-3xl text-primary dark:text-white" @click="themeSwitch()"
                :class="isDarkMode ? 'bxs-sun' : 'bxs-moon'"></i>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div
      class="pointer-events-none fixed inset-0 z-50 flex bg-black bg-opacity-80 opacity-0 transition-opacity lg:hidden"
      :class="isMobileMenuOpen ? 'opacity-100 pointer-events-auto' : ''">
      <div class="ml-auto w-2/3 bg-green p-4 md:w-1/3">
        <i class="bx bx-x absolute top-0 right-0 mt-4 mr-4 text-4xl text-white" @click="isMobileMenuOpen = false"></i>
        <ul class="mt-8 flex flex-col">

          <li class="">
            <a href="/" class="mb-3 block px-2 font-body text-lg font-medium text-white">Intro</a>
          </li>

          <li class="">
            <a href="/blog" class="mb-3 block px-2 font-body text-lg font-medium text-white">Blog</a>
          </li>

          <li class="">
            <a href="/uses" class="mb-3 block px-2 font-body text-lg font-medium text-white">Sign Out</a>
          </li>

          <li class="">
            <a href="/contact" class="mb-3 block px-2 font-body text-lg font-medium text-white">Edit Profile</a>
          </li>

        </ul>
      </div>

</div>